[package]
name = "rfb_labs_week_6"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bitcoin = { version = "0.32.5", features = ["serde"] }
bitcoincore-rpc = "0.19"
clap = { version = "4.5", features = ["derive", "env"] }
miniscript = { version = "12", features = ["compiler", "serde"] }
rand = "0.8"
rusqlite = { version = "0.32", features = ["bundled"] }
