//! Wallet lifecycle: `init` (generate + persist a brand new wallet) and `open` (load an existing
//! one for every other command).

use std::fs;
use std::io::Write;
use std::path::Path;

use anyhow::{Context, Result, bail};
use bdk_wallet::rusqlite::Connection;
use bdk_wallet::{KeychainKind, PersistedWallet, Wallet as WalletBuilder};

use crate::config::{Config, DescriptorKind};
use crate::keys::{self, GeneratedWallet};

/// A wallet bound to its SQLite persister, as returned by `bdk_wallet::Wallet`'s `create_wallet`/
/// `load_wallet` builder methods. `PersistedWallet` derefs to `bdk_wallet::Wallet`, so every
/// read-only wallet method (balance, list_unspent, build_tx, ...) is available directly;
/// `.persist()` itself is only defined here, on `PersistedWallet`.
pub type Wallet = PersistedWallet<Connection>;

/// The `.env` file `init` writes and every other command reads its descriptors from.
const ENV_PATH: &str = ".env";

/// Open the SQLite persister for `cfg.db_path`, creating the file if it doesn't exist yet.
fn open_db(cfg: &Config) -> Result<Connection> {
    Connection::open(&cfg.db_path).with_context(|| {
        format!(
            "failed to open wallet database at {}",
            cfg.db_path.display()
        )
    })
}

/// Load a previously-`init`'d wallet. Fails with a clear message if `init` hasn't been run (no
/// descriptor configured, or no matching data in the database).
pub fn open(cfg: &Config) -> Result<(Wallet, Connection)> {
    let descriptor = cfg.descriptor.clone().context(
        "no DESCRIPTOR configured — run `init` first (or set DESCRIPTOR/CHANGE_DESCRIPTOR)",
    )?;
    let mut db = open_db(cfg)?;

    let wallet = WalletBuilder::load()
        .descriptor(KeychainKind::External, Some(descriptor))
        .descriptor(KeychainKind::Internal, cfg.change_descriptor.clone())
        .check_network(cfg.network)
        // Our descriptors embed private keys (`tprv...`); without this, `load()` only checks
        // them against the persisted public descriptor and the wallet comes back unable to sign.
        .extract_keys()
        .load_wallet(&mut db)
        .context("failed to load wallet from database")?
        .context("wallet database exists but has no wallet data — run `init` first")?;

    Ok((wallet, db))
}

/// Generate a fresh key, derive a wallet from its descriptor, persist the empty wallet, and write
/// `.env` so future commands can reopen it. Refuses to overwrite an existing `.env` or database
/// unless `force` is set.
pub fn init(
    cfg: &Config,
    kind: DescriptorKind,
    force: bool,
) -> Result<(Wallet, Connection, GeneratedWallet)> {
    if !force {
        if Path::new(ENV_PATH).exists() {
            bail!(
                "{ENV_PATH} already exists — pass --force to overwrite it and start a new wallet"
            );
        }
        if cfg.db_path.exists() {
            bail!(
                "{} already exists — pass --force to overwrite it and start a new wallet",
                cfg.db_path.display()
            );
        }
    } else if cfg.db_path.exists() {
        fs::remove_file(&cfg.db_path)
            .with_context(|| format!("failed to remove {}", cfg.db_path.display()))?;
    }

    let generated = keys::generate(cfg.network, kind)?;
    let mut db = open_db(cfg)?;

    let wallet = WalletBuilder::create(
        generated.external_descriptor.clone(),
        generated.internal_descriptor.clone(),
    )
    .network(cfg.network)
    .create_wallet(&mut db)
    .context("failed to create wallet")?;

    write_env_file(cfg, &generated)?;

    Ok((wallet, db, generated))
}

fn write_env_file(cfg: &Config, generated: &GeneratedWallet) -> Result<()> {
    let mut file =
        fs::File::create(ENV_PATH).with_context(|| format!("failed to create {ENV_PATH}"))?;
    writeln!(
        file,
        "# Generated by `init` — DO NOT COMMIT THIS FILE (it is already .gitignored)."
    )?;
    writeln!(
        file,
        "# MNEMONIC is kept only for human backup; the program itself only reads the"
    )?;
    writeln!(
        file,
        "# descriptors below, which already embed the derived private key."
    )?;
    writeln!(file, "MNEMONIC=\"{}\"", generated.mnemonic)?;
    writeln!(file, "BITCOIN_NETWORK={}", cfg.network)?;
    writeln!(file, "DESCRIPTOR=\"{}\"", generated.external_descriptor)?;
    writeln!(
        file,
        "CHANGE_DESCRIPTOR=\"{}\"",
        generated.internal_descriptor
    )?;
    writeln!(file, "BDK_DB_PATH={}", cfg.db_path.display())?;
    writeln!(file, "RPC_URL={}", cfg.rpc_url)?;
    if let Some(cookie) = &cfg.rpc_cookie {
        writeln!(file, "RPC_COOKIE={}", cookie.display())?;
    }
    Ok(())
}
