//! Lab 03 evidence runner.
//!
//! Usage: cargo run --example lab03 [-- <miner_address> <receiver_address>]
//!
//! Defaults to the addresses generated by `examples/lab02.rs`. Pass your own
//! as positional args if you regenerated them.

use rfb_labs_week_1::labs::lab03_maturity::demonstrate_coinbase_maturity;
use rfb_labs_week_1::rpc::ProcessRpc;

const DEFAULT_MINER_ADDRESS: &str = "bcrt1qsfqwvhu2yn2ghu5yj2dsajdck38gykmk0nq7cn";
const DEFAULT_RECEIVER_ADDRESS: &str = "bcrt1q6nlqtswveesh573tml9mrwlczn66vfu0sjnaqn";

fn main() {
    let mut args = std::env::args().skip(1);
    let miner_address = args
        .next()
        .unwrap_or_else(|| DEFAULT_MINER_ADDRESS.to_owned());
    let receiver_address = args
        .next()
        .unwrap_or_else(|| DEFAULT_RECEIVER_ADDRESS.to_owned());

    let rpc = ProcessRpc::new("bitcoin-cli").with_base_args([
        "-regtest",
        "-rpcport=18443",
        "-rpcuser=polaruser",
        "-rpcpassword=polarpass",
    ]);

    let report = demonstrate_coinbase_maturity(&rpc, "miner", &miner_address, &receiver_address)
        .expect("demonstrate coinbase maturity");

    println!(
        "height after first block: {}",
        report.height_after_first_block
    );
    println!(
        "balance after first block: trusted={} untrusted_pending={} immature={}",
        report.balance_after_first_block.trusted,
        report.balance_after_first_block.untrusted_pending,
        report.balance_after_first_block.immature
    );
    println!(
        "premature 1 BTC spend error: {}",
        report.premature_spend_error
    );
    println!("final height: {}", report.final_height);
    println!(
        "final balance: trusted={} untrusted_pending={} immature={}",
        report.final_balance.trusted,
        report.final_balance.untrusted_pending,
        report.final_balance.immature
    );
}
